# Generated by Django 5.0.14 on 2026-05-10 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('business_profile', 'Business profile'), ('packages_catalogue', 'Packages catalogue'), ('instant_quote', 'Instant quote'), ('package_brochure', 'Package brochure'), ('product_brochure', 'Product brochure'), ('other', 'Other')], db_index=True, max_length=32)),
                ('surface', models.CharField(choices=[('contact_page', 'Contact page'), ('about_page', 'About page'), ('nav_dropdown', 'Nav dropdown'), ('packages_page', 'Packages listing'), ('package_detail', 'Package detail'), ('product_detail', 'Product detail'), ('solar_advisor', 'Solar Advisor'), ('package_card', 'Family card'), ('admin', 'Admin dashboard'), ('direct_link', 'Direct link'), ('other', 'Other')], db_index=True, default='other', max_length=32)),
                ('target_slug', models.CharField(blank=True, db_index=True, max_length=200)),
                ('target_label', models.CharField(blank=True, help_text='Human-readable name', max_length=200)),
                ('target_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(db_index=True, default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Download',
                'verbose_name_plural': 'Downloads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='downloads_d_kind_e62483_idx'), models.Index(fields=['surface', '-created_at'], name='downloads_d_surface_c065e7_idx'), models.Index(fields=['success', '-created_at'], name='downloads_d_success_74f66c_idx')],
            },
        ),
    ]
