# Generated by Django 5.0.14 on 2026-08-31 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='Smart Solar Choices Zimbabwe', help_text='Small label under the title (e.g. the channel name).', max_length=120)),
                ('youtube_url', models.CharField(help_text='Any YouTube link — watch, youtu.be, or embed URL.', max_length=500)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Video story',
                'verbose_name_plural': 'Video stories',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
