# Generated by Django 5.0.14 on 2026-06-10 18:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=20)),
                ('target_type', models.CharField(choices=[('supplier', 'Supplier'), ('material', 'Material'), ('price', 'Supplier Price'), ('quotation', 'Quotation'), ('category', 'Category')], db_index=True, max_length=20)),
                ('target_name', models.CharField(max_length=300)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', '-created_at'], name='inventory_a_target__6b0cf1_idx'), models.Index(fields=['action', '-created_at'], name='inventory_a_action_4c2c92_idx')],
            },
        ),
    ]
