# Generated by Django 5.0.14 on 2026-06-11 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auditlog'),
        ('shop', '0005_seed_geyser_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_materials', to='shop.product'),
        ),
    ]
