# Generated by Django 5.0.14 on 2026-06-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='markup_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
