# Generated by Django 5.0.14 on 2026-06-11 13:33

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeyserPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('system_type', models.CharField(choices=[('gravity', 'Gravity (Non-Pressure)'), ('pressure', 'Pressure')], db_index=True, max_length=10)),
                ('capacity_litres', models.PositiveIntegerField(db_index=True)),
                ('variant', models.CharField(choices=[('standard', 'Standard'), ('smart', 'Smart')], db_index=True, max_length=10)),
                ('is_smart', models.BooleanField(db_index=True, default=False)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('geyser_unit', models.CharField(blank=True, help_text='The main collector/tank', max_length=160)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sundries_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('whats_included', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=list)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('components', models.JSONField(blank=True, default=list, help_text='Bill of materials: [{name, qty, unit_price}]')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'system_type', 'capacity_litres', 'variant'],
                'indexes': [models.Index(fields=['system_type', 'capacity_litres'], name='geysers_gey_system__80f552_idx'), models.Index(fields=['is_active', 'sort_order'], name='geysers_gey_is_acti_7b5a1e_idx')],
            },
        ),
    ]
