# Generated by Django 5.0.14 on 2026-08-31 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('institutional', 'Institutional'), ('agricultural', 'Agricultural'), ('other', 'Other')], db_index=True, default='residential', max_length=30)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('kva', models.CharField(blank=True, help_text='e.g. "24kVA"', max_length=50)),
                ('date_label', models.CharField(blank=True, help_text='Display date, e.g. "Feb 2023"', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('hero_image_url', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, help_text='Short summary shown on cards.')),
                ('full_description', models.JSONField(blank=True, default=list, help_text='List of paragraphs.')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Key/value system specs.')),
                ('benefits', models.JSONField(blank=True, default=list, help_text='List of benefit bullets.')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_published', 'sort_order'], name='projects_pr_is_publ_ddecba_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'is_published'], name='projects_pr_categor_bc37c5_idx'),
        ),
    ]
