# Generated by Django 5.0.14 on 2026-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_cta_label_project_cta_type_project_cta_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_url',
            field=models.CharField(blank=True, help_text='YouTube link to feature on the project page.', max_length=500, null=True),
        ),
    ]
