# Generated by Django 5.0.14 on 2026-03-02 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_app_order_update', models.BooleanField(default=True)),
                ('in_app_payment_received', models.BooleanField(default=True)),
                ('in_app_quote_ready', models.BooleanField(default=True)),
                ('in_app_job_assigned', models.BooleanField(default=True)),
                ('in_app_ticket_reply', models.BooleanField(default=True)),
                ('in_app_course_update', models.BooleanField(default=True)),
                ('in_app_promotion', models.BooleanField(default=True)),
                ('in_app_system', models.BooleanField(default=True)),
                ('email_order_update', models.BooleanField(default=True)),
                ('email_payment_received', models.BooleanField(default=True)),
                ('email_quote_ready', models.BooleanField(default=True)),
                ('email_job_assigned', models.BooleanField(default=True)),
                ('email_ticket_reply', models.BooleanField(default=True)),
                ('email_course_update', models.BooleanField(default=False)),
                ('email_promotion', models.BooleanField(default=False)),
                ('email_system', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('payment_received', 'Payment Received'), ('quote_ready', 'Quotation Ready'), ('job_assigned', 'Job Assigned'), ('ticket_reply', 'Ticket Reply'), ('course_update', 'Course Update'), ('promotion', 'Promotion'), ('system', 'System')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, help_text='Frontend route to navigate to', max_length=500)),
                ('action_label', models.CharField(blank=True, help_text='Button text e.g. "View Order"', max_length=100)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('ticket_id', models.UUIDField(blank=True, null=True)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('course_id', models.UUIDField(blank=True, null=True)),
                ('quotation_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx'), models.Index(fields=['user', 'notification_type'], name='notificatio_user_id_f77590_idx')],
            },
        ),
    ]
