# Generated by Django 5.0.14 on 2026-09-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cta_label',
            field=models.CharField(blank=True, help_text='Custom button text (cta_type = custom).', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_type',
            field=models.CharField(choices=[('quote', 'Get a Free Quote'), ('contact', 'Contact Us'), ('whatsapp', 'WhatsApp Us'), ('call', 'Call Us'), ('packages', 'View Packages'), ('shop', 'Shop Equipment'), ('advisor', 'Try the Solar Advisor'), ('custom', 'Custom (set label + link)'), ('none', 'No button')], default='quote', max_length=20),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Custom button link (cta_type = custom).', max_length=500),
        ),
    ]
