# Generated by Django 5.0.14 on 2026-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_cta_label_blogpost_cta_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.CharField(blank=True, help_text='YouTube link to embed in the article.', max_length=500, null=True),
        ),
    ]
