# Generated by Django 5.0.14 on 2026-03-02 18:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0001_initial'),
        ('shop', '0001_initial'),
        ('solar_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('job_type', models.CharField(choices=[('installation', 'Installation'), ('maintenance', 'Maintenance'), ('repair', 'Repair'), ('inspection', 'Inspection'), ('consultation', 'Consultation')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='unassigned', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, choices=[('harare', 'Harare'), ('bulawayo', 'Bulawayo'), ('manicaland', 'Manicaland'), ('mashonaland_central', 'Mashonaland Central'), ('mashonaland_east', 'Mashonaland East'), ('mashonaland_west', 'Mashonaland West'), ('masvingo', 'Masvingo'), ('matabeleland_north', 'Matabeleland North'), ('matabeleland_south', 'Matabeleland South'), ('midlands', 'Midlands')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time_start', models.TimeField(blank=True, null=True)),
                ('scheduled_time_end', models.TimeField(blank=True, null=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, default=2, help_text='Estimated job duration in hours', max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('system_details', models.JSONField(blank=True, default=dict, help_text='System details: panel count, inverter, battery, etc.')),
                ('materials_used', models.JSONField(blank=True, default=list, help_text='List of materials/parts used during the job')),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('customer_feedback', models.TextField(blank=True)),
                ('completion_summary', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_assigned', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='shop.order')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='quotations.quotation')),
                ('solar_configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_jobs', to='solar_config.solarconfiguration')),
            ],
            options={
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal notes not visible to customer')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_notes', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='technicians.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='job_photos/%Y/%m/')),
                ('image_url', models.URLField(blank=True, help_text='External URL alternative')),
                ('photo_type', models.CharField(choices=[('before', 'Before Work'), ('during', 'During Work'), ('after', 'After Work'), ('issue', 'Issue/Problem'), ('material', 'Materials Used')], default='during', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='technicians.job')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['photo_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='technicians.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('skill_level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid-Level'), ('senior', 'Senior'), ('lead', 'Lead')], default='junior', max_length=20)),
                ('specializations', models.JSONField(blank=True, default=list, help_text='List of specialization areas, e.g. ["installation", "repair", "battery"]')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='List of certifications, e.g. [{"name": "ZERA Licensed", "year": 2023}]')),
                ('service_provinces', models.JSONField(blank=True, default=list, help_text='List of province codes the technician covers')),
                ('service_radius_km', models.PositiveIntegerField(default=50)),
                ('base_location', models.CharField(blank=True, help_text='Home base / depot address', max_length=200)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('max_concurrent_jobs', models.PositiveIntegerField(default=3)),
                ('total_jobs_completed', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.PositiveIntegerField(default=0)),
                ('on_time_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-average_rating', 'user__first_name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='technicians.technicianprofile'),
        ),
        migrations.CreateModel(
            name='TechnicianSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule_type', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('leave', 'On Leave'), ('training', 'Training')], default='available', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='technicians.technicianprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'technician'], name='technicians_status_25a10b_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['scheduled_date', 'status'], name='technicians_schedul_4aff7f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['customer', 'status'], name='technicians_custome_47eb2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianschedule',
            unique_together={('technician', 'date', 'start_time')},
        ),
    ]
