# Generated by Django 5.0.14 on 2026-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(blank=True, help_text='Image URL or path (alternative to upload)', max_length=500),
        ),
    ]
