# Generated by Django 5.0.14 on 2026-06-16 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_seed_geyser_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_product_ordering', models.CharField(choices=[('featured', 'Featured first'), ('newest', 'Newest first'), ('oldest', 'Oldest first'), ('price_asc', 'Price: low to high'), ('price_desc', 'Price: high to low'), ('name', 'Name: A to Z'), ('rating', 'Top rated')], default='newest', help_text='Default order products appear in the shop (when the visitor has not picked a sort).', max_length=20)),
            ],
            options={
                'verbose_name': 'Shop setting',
                'verbose_name_plural': 'Shop settings',
            },
        ),
    ]
