# Generated by Django 5.0.14 on 2026-05-08 05:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Stable machine identifier — referenced by frontend gates.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human-readable name shown in the admin dashboard.', max_length=128)),
                ('description', models.TextField(blank=True, help_text='What this feature does — shown to admins as context.')),
                ('is_enabled', models.BooleanField(default=False, help_text='Master switch. If false, the feature is locked for everyone.')),
                ('enabled_for_staff_only', models.BooleanField(default=False, help_text='If true, only authenticated staff users see the feature live.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'ordering': ['name'],
            },
        ),
    ]
