# Generated by Django 5.0.14 on 2026-05-10 20:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('area', models.CharField(blank=True, help_text='Suburb / town the system will be installed.', max_length=200)),
                ('distance_km', models.PositiveIntegerField(blank=True, help_text='Distance from Taqon HQ.', null=True)),
                ('monthly_grid_bill', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate current monthly electricity bill (USD).', max_digits=10, null=True)),
                ('appliances', models.JSONField(blank=True, default=list, help_text='Selected appliances and quantities — same shape as Solar Advisor.')),
                ('message', models.TextField(blank=True, help_text='Free-form notes from the customer.')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost'), ('archived', 'Archived')], db_index=True, default='new', max_length=20)),
                ('source', models.CharField(choices=[('public_form', 'Public form'), ('whatsapp_link', 'WhatsApp link'), ('email_link', 'Email link'), ('shop_request', 'Shop checkout request'), ('other', 'Other')], default='public_form', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes — never shown to the customer.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Inquiry',
                'verbose_name_plural': 'Customer Inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='inquiries_i_status_152cc6_idx'), models.Index(fields=['email'], name='inquiries_i_email_415ef2_idx')],
            },
        ),
    ]
