# Generated by Django 5.0.14 on 2026-03-03 07:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='e.g. Home, Office, Site', max_length=50)),
                ('recipient_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address_line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(choices=[('harare', 'Harare'), ('bulawayo', 'Bulawayo'), ('manicaland', 'Manicaland'), ('mashonaland_central', 'Mashonaland Central'), ('mashonaland_east', 'Mashonaland East'), ('mashonaland_west', 'Mashonaland West'), ('masvingo', 'Masvingo'), ('matabeleland_north', 'Matabeleland North'), ('matabeleland_south', 'Matabeleland South'), ('midlands', 'Midlands')], max_length=50)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saved Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
