"""Solar geyser package seed data — generated from "geysers packages.xlsx".
16 packages: gravity/pressure x 100/150/200/300L x standard/smart."""

GEYSER_PACKAGES = [{'name': '100L Gravity Standard',
  'system_type': 'gravity',
  'capacity_litres': 100,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Ecosolar',
  'geyser_unit': '100L Gravity Ecosolar',
  'price': 791.69,
  'material_cost': 597.1,
  'sundries_cost': 29.85,
  'labour_cost': 188.09,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '100L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 348.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5}],
  'whats_included': ['100L Gravity Ecosolar',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '100 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Standard',
                     'Collector brand': 'Ecosolar',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '100L gravity-fed (non-pressure) solar geyser, supplied & installed.',
  'description': 'A complete 100-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 0},
 {'name': '100L Gravity Smart',
  'system_type': 'gravity',
  'capacity_litres': 100,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Ecosolar',
  'geyser_unit': '100L Gravity Ecosolar',
  'price': 1193.42,
  'material_cost': 902.6,
  'sundries_cost': 45.13,
  'labour_cost': 284.32,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '100L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 348.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['100L Gravity Ecosolar',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '100 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Ecosolar',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '100L gravity-fed (non-pressure) solar geyser with an intelligent controller, supplied & '
                       'installed.',
  'description': 'A complete 100-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation. This '
                 'Smart version adds an intelligent solar geyser controller with up to five programmable heating '
                 'schedules a day for automatic temperature control and extra electricity savings.',
  'sort_order': 1},
 {'name': '150L Gravity Standard',
  'system_type': 'gravity',
  'capacity_litres': 150,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Ecosolar',
  'geyser_unit': '150L Gravity Ecosolar',
  'price': 878.81,
  'material_cost': 663.35,
  'sundries_cost': 33.17,
  'labour_cost': 208.96,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '150L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 415},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5}],
  'whats_included': ['150L Gravity Ecosolar',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '150 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Standard',
                     'Collector brand': 'Ecosolar',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '150L gravity-fed (non-pressure) solar geyser, supplied & installed.',
  'description': 'A complete 150-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 2},
 {'name': '150L Gravity Smart',
  'system_type': 'gravity',
  'capacity_litres': 150,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Ecosolar',
  'geyser_unit': '150L Gravity Ecosolar',
  'price': 1280.54,
  'material_cost': 968.85,
  'sundries_cost': 48.44,
  'labour_cost': 305.19,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '150L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 415},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['150L Gravity Ecosolar',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '150 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Ecosolar',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '150L gravity-fed (non-pressure) solar geyser with an intelligent controller, supplied & '
                       'installed.',
  'description': 'A complete 150-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation. This '
                 'Smart version adds an intelligent solar geyser controller with up to five programmable heating '
                 'schedules a day for automatic temperature control and extra electricity savings.',
  'sort_order': 3},
 {'name': '200L Gravity Standard',
  'system_type': 'gravity',
  'capacity_litres': 200,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Ecosolar',
  'geyser_unit': '200L Gravity Ecosolar',
  'price': 986.81,
  'material_cost': 745.48,
  'sundries_cost': 37.27,
  'labour_cost': 234.83,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '200L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 460.13},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 3, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5}],
  'whats_included': ['200L Gravity Ecosolar',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '200 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Standard',
                     'Collector brand': 'Ecosolar',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '200L gravity-fed (non-pressure) solar geyser, supplied & installed.',
  'description': 'A complete 200-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 4},
 {'name': '200L Gravity Smart',
  'system_type': 'gravity',
  'capacity_litres': 200,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Ecosolar',
  'geyser_unit': '200L Gravity Ecosolar',
  'price': 1388.54,
  'material_cost': 1050.98,
  'sundries_cost': 52.55,
  'labour_cost': 331.06,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '200L GRAVITY ECOSOLAR', 'qty': 1, 'unit_price': 460.13},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 3, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['200L Gravity Ecosolar',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '200 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Ecosolar',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '200L gravity-fed (non-pressure) solar geyser with an intelligent controller, supplied & '
                       'installed.',
  'description': 'A complete 200-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Ecosolar collector and supplied with all plumbing, mounting and professional installation. This '
                 'Smart version adds an intelligent solar geyser controller with up to five programmable heating '
                 'schedules a day for automatic temperature control and extra electricity savings.',
  'sort_order': 5},
 {'name': '300L Gravity Standard',
  'system_type': 'gravity',
  'capacity_litres': 300,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Electrosales',
  'geyser_unit': '300L Gravity Electrosales',
  'price': 1538.08,
  'material_cost': 1164.7,
  'sundries_cost': 58.24,
  'labour_cost': 366.88,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '300L GRAVITY ELECTROSALES', 'qty': 1, 'unit_price': 898.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 8, 'unit_price': 3.5}],
  'whats_included': ['300L Gravity Electrosales',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '300 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Standard',
                     'Collector brand': 'Electrosales',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '300L gravity-fed (non-pressure) solar geyser, supplied & installed.',
  'description': 'A complete 300-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Electrosales collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 6},
 {'name': '300L Gravity Smart',
  'system_type': 'gravity',
  'capacity_litres': 300,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Electrosales',
  'geyser_unit': '300L Gravity Electrosales',
  'price': 1939.81,
  'material_cost': 1470.2,
  'sundries_cost': 73.51,
  'labour_cost': 463.11,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '300L GRAVITY ELECTROSALES', 'qty': 1, 'unit_price': 898.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 1, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 1, 'unit_price': 58},
                 {'name': 'COBRA BALL VALVE 15MM NICKEL PLATED', 'qty': 1, 'unit_price': 8.5},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 1, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 5, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 8, 'unit_price': 3.5},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['300L Gravity Electrosales',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Reliable gravity-fed (non-pressure) operation',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '300 litres',
                     'System': 'Gravity (non-pressure)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Electrosales',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '300L gravity-fed (non-pressure) solar geyser with an intelligent controller, supplied & '
                       'installed.',
  'description': 'A complete 300-litre non-pressure (gravity) solar geyser system from Taqon Electrico, built around a '
                 'Electrosales collector and supplied with all plumbing, mounting and professional installation. This '
                 'Smart version adds an intelligent solar geyser controller with up to five programmable heating '
                 'schedules a day for automatic temperature control and extra electricity savings.',
  'sort_order': 7},
 {'name': '100L Pressure Standard',
  'system_type': 'pressure',
  'capacity_litres': 100,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Suntask',
  'geyser_unit': '100L Pressure Suntask',
  'price': 1835.93,
  'material_cost': 1391.2,
  'sundries_cost': 69.56,
  'labour_cost': 438.23,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '100L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 760},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7}],
  'whats_included': ['100L Pressure Suntask',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '100 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Standard',
                     'Collector brand': 'Suntask',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '100L pressure (mains) solar geyser, supplied & installed.',
  'description': 'A complete 100-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 8},
 {'name': '100L Pressure Smart',
  'system_type': 'pressure',
  'capacity_litres': 100,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Suntask',
  'geyser_unit': '100L Pressure Suntask',
  'price': 2237.66,
  'material_cost': 1696.7,
  'sundries_cost': 84.84,
  'labour_cost': 534.46,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '100L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 760},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['100L Pressure Suntask',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '100 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Suntask',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '100L pressure (mains) solar geyser with an intelligent controller, supplied & installed.',
  'description': 'A complete 100-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation. This Smart version '
                 'adds an intelligent solar geyser controller with up to five programmable heating schedules a day for '
                 'automatic temperature control and extra electricity savings.',
  'sort_order': 9},
 {'name': '150L Pressure Standard',
  'system_type': 'pressure',
  'capacity_litres': 150,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Suntask',
  'geyser_unit': '150L Pressure Suntask',
  'price': 2225.96,
  'material_cost': 1687.8,
  'sundries_cost': 84.39,
  'labour_cost': 531.66,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '150L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 1053},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7}],
  'whats_included': ['150L Pressure Suntask',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '150 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Standard',
                     'Collector brand': 'Suntask',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '150L pressure (mains) solar geyser, supplied & installed.',
  'description': 'A complete 150-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 10},
 {'name': '150L Pressure Smart',
  'system_type': 'pressure',
  'capacity_litres': 150,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Suntask',
  'geyser_unit': '150L Pressure Suntask',
  'price': 2627.69,
  'material_cost': 1993.3,
  'sundries_cost': 99.67,
  'labour_cost': 627.89,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '150L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 1053},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['150L Pressure Suntask',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '150 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Suntask',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '150L pressure (mains) solar geyser with an intelligent controller, supplied & installed.',
  'description': 'A complete 150-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation. This Smart version '
                 'adds an intelligent solar geyser controller with up to five programmable heating schedules a day for '
                 'automatic temperature control and extra electricity savings.',
  'sort_order': 11},
 {'name': '200L Pressure Standard',
  'system_type': 'pressure',
  'capacity_litres': 200,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Suntask',
  'geyser_unit': '200L Pressure Suntask',
  'price': 2660.89,
  'material_cost': 2018.55,
  'sundries_cost': 100.93,
  'labour_cost': 635.84,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '200L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 1383.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7}],
  'whats_included': ['200L Pressure Suntask',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '200 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Standard',
                     'Collector brand': 'Suntask',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '200L pressure (mains) solar geyser, supplied & installed.',
  'description': 'A complete 200-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 12},
 {'name': '200L Pressure Smart',
  'system_type': 'pressure',
  'capacity_litres': 200,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Suntask',
  'geyser_unit': '200L Pressure Suntask',
  'price': 3062.63,
  'material_cost': 2324.05,
  'sundries_cost': 116.2,
  'labour_cost': 732.08,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '200L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 1383.75},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 2, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 4, 'unit_price': 3.5},
                 {'name': '400kpa PRESSUR CONTROL VALVE', 'qty': 1, 'unit_price': 124},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7},
                 {'name': '1500W SOLAR GEYSER ELEMENT', 'qty': 1, 'unit_price': 45},
                 {'name': 'INTERLLIGENT SOLAR GEYSER CONTROLLER', 'qty': 1, 'unit_price': 156},
                 {'name': '40 BY 40 PVC TRUNKING', 'qty': 1, 'unit_price': 12},
                 {'name': '2.5MM FLEX CABLE', 'qty': 30, 'unit_price': 2.85},
                 {'name': '20A SINGLE POLE AC MCB', 'qty': 1, 'unit_price': 7}],
  'whats_included': ['200L Pressure Suntask',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '200 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Suntask',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '200L pressure (mains) solar geyser with an intelligent controller, supplied & installed.',
  'description': 'A complete 200-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation. This Smart version '
                 'adds an intelligent solar geyser controller with up to five programmable heating schedules a day for '
                 'automatic temperature control and extra electricity savings.',
  'sort_order': 13},
 {'name': '300L Pressure Standard',
  'system_type': 'pressure',
  'capacity_litres': 300,
  'variant': 'standard',
  'is_smart': False,
  'brand': 'Suntask',
  'geyser_unit': '300L Pressure Suntask',
  'price': 3471.59,
  'material_cost': 2635.05,
  'sundries_cost': 131.75,
  'labour_cost': 830.04,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '300L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 2036.25},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 4, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 8, 'unit_price': 3.5},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7}],
  'whats_included': ['300L Pressure Suntask',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support'],
  'specifications': {'Capacity': '300 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Standard',
                     'Collector brand': 'Suntask',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '300L pressure (mains) solar geyser, supplied & installed.',
  'description': 'A complete 300-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation.',
  'sort_order': 14},
 {'name': '300L Pressure Smart',
  'system_type': 'pressure',
  'capacity_litres': 300,
  'variant': 'smart',
  'is_smart': True,
  'brand': 'Suntask',
  'geyser_unit': '300L Pressure Suntask',
  'price': 3471.59,
  'material_cost': 2635.05,
  'sundries_cost': 131.75,
  'labour_cost': 830.04,
  'transport_cost': 6.5,
  'distance_km': 10,
  'components': [{'name': '300L PRESSURE SUNTASK', 'qty': 1, 'unit_price': 2036.25},
                 {'name': '250G SOLDERING FLUX', 'qty': 1, 'unit_price': 12},
                 {'name': '250G SOLADERING RESIN CORE', 'qty': 1, 'unit_price': 23},
                 {'name': 'FENDER WASHERS PACK OF 20', 'qty': 5, 'unit_price': 1.2},
                 {'name': 'M8 HOOK BOLTS AND NUTS', 'qty': 8, 'unit_price': 1.2},
                 {'name': 'GAS CANISTER', 'qty': 2, 'unit_price': 4},
                 {'name': 'COPPER CAPILLARY COUPLER 15MM X 1/2IN CXMi DELCOP', 'qty': 2, 'unit_price': 0.85},
                 {'name': 'COPPER CAPILLARY COUPLER 22MM X 3/4INCH CxMi DELCOP', 'qty': 10, 'unit_price': 1.4},
                 {'name': 'COPPER TAP ADAPTER 15MM', 'qty': 1, 'unit_price': 4},
                 {'name': 'COPPER PIPE 15MM X 0.5 X 5.5M', 'qty': 4, 'unit_price': 37},
                 {'name': 'COPPER PIPE 22MM X 0.6 X 5.5M CLASS 0', 'qty': 3, 'unit_price': 58},
                 {'name': 'BALL VALVE 20MM NICKEL PLATED', 'qty': 2, 'unit_price': 13},
                 {'name': 'GALVANIZED IRON MOUNTING RAILS 6M', 'qty': 1, 'unit_price': 15},
                 {'name': 'THREAD TAPE', 'qty': 10, 'unit_price': 0.75},
                 {'name': 'TILE HOOKS', 'qty': 8, 'unit_price': 3.5},
                 {'name': 'VACUUM BREAKER', 'qty': 2, 'unit_price': 34},
                 {'name': '20MM NON-RETURN VALVE', 'qty': 1, 'unit_price': 12},
                 {'name': '22MM COPPER TEE CAPILLARY', 'qty': 4, 'unit_price': 8},
                 {'name': '22MMX15MM COPPER REDUCERS', 'qty': 2, 'unit_price': 2.3},
                 {'name': '22MM COPPER COUPLERS Cu-Cu', 'qty': 2, 'unit_price': 2.7}],
  'whats_included': ['300L Pressure Suntask',
                     'Intelligent solar geyser controller (up to 5 daily schedules)',
                     '1500W backup heating element',
                     'Dedicated geyser circuit & MCB',
                     'Galvanised mounting rails, hooks & roof fixings',
                     'Complete copper plumbing kit — pipes, couplers, valves & fittings',
                     '400kPa pressure control valve, vacuum breakers & non-return valve',
                     'Professional installation, soldering & commissioning (skilled labour)'],
  'features': ['Free hot water heated by the sun',
               'Mains-pressure hot water to every tap & shower',
               "Cuts your geyser's electricity bill",
               'Quality collector with strong local warranty support',
               'Intelligent temperature management',
               'Automatic water temperature maintenance',
               'Up to 5 programmable heating schedules per day',
               'Improved electricity savings',
               'Improved comfort and convenience'],
  'specifications': {'Capacity': '300 litres',
                     'System': 'Pressure (mains)',
                     'Version': 'Smart (intelligent controller)',
                     'Collector brand': 'Suntask',
                     'Heating schedules': 'Up to 5 per day',
                     'Backup element': '1500W',
                     'Installation': 'Included (within 10 km of Harare; $0.65/km beyond)'},
  'short_description': '300L pressure (mains) solar geyser with an intelligent controller, supplied & installed.',
  'description': 'A complete 300-litre pressure solar geyser system from Taqon Electrico, built around a Suntask '
                 'collector and supplied with all plumbing, mounting and professional installation. This Smart version '
                 'adds an intelligent solar geyser controller with up to five programmable heating schedules a day for '
                 'automatic temperature control and extra electricity savings.',
  'sort_order': 15}]
