# Generated by Django 5.0.14 on 2026-03-02 17:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('category', models.CharField(choices=[('panel', 'Solar Panel'), ('inverter', 'Inverter'), ('battery', 'Battery'), ('charger', 'Charge Controller'), ('mounting', 'Mounting Structure'), ('cable', 'Cable & Wiring'), ('accessory', 'Accessory')], db_index=True, max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('wattage', models.PositiveIntegerField(default=0, help_text='Watts (panels: peak watts, inverters: VA rating)')),
                ('voltage', models.DecimalField(decimal_places=1, default=0, help_text='Nominal voltage', max_digits=6)),
                ('capacity_ah', models.DecimalField(decimal_places=1, default=0, help_text='Battery capacity in Ah', max_digits=8)),
                ('capacity_kwh', models.DecimalField(decimal_places=2, default=0, help_text='Battery capacity in kWh', max_digits=8)),
                ('efficiency', models.DecimalField(decimal_places=2, default=0, help_text='Efficiency percentage', max_digits=5)),
                ('warranty_years', models.PositiveIntegerField(default=0)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('compatible_voltages', models.JSONField(blank=True, default=list, help_text='List of compatible system voltages [12, 24, 48]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solar_components', to='shop.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SolarConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Solar System', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_wattage', models.PositiveIntegerField(default=0, help_text='Total panel wattage')),
                ('system_voltage', models.PositiveIntegerField(default=48, help_text='System voltage (12/24/48)')),
                ('estimated_daily_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_backup_hours', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('quoted', 'Converted to Quote')], default='draft', max_length=20)),
                ('has_warnings', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_uses', to='solar_config.solarcomponent')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solar_config.solarconfiguration')),
            ],
            options={
                'ordering': ['component__category', 'component__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SolarPackageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('popular', 'Popular'), ('premium', 'Premium'), ('commercial', 'Commercial')], default='starter', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('system_size_kw', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('inverter_rating_va', models.PositiveIntegerField(default=0, help_text='Inverter VA rating')),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('estimated_daily_output_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('backup_hours', models.DecimalField(decimal_places=1, default=0, help_text='Estimated backup hours at average load', max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('features', models.JSONField(blank=True, default=list)),
                ('suitable_for', models.JSONField(blank=True, default=list, help_text='e.g., ["residential", "small_business"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='solarconfiguration',
            name='based_on_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_configs', to='solar_config.solarpackagetemplate'),
        ),
        migrations.CreateModel(
            name='PackageComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_uses', to='solar_config.solarcomponent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='solar_config.solarpackagetemplate')),
            ],
            options={
                'ordering': ['component__category', 'component__sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='solarcomponent',
            index=models.Index(fields=['category', 'is_active'], name='solar_confi_categor_fa0943_idx'),
        ),
        migrations.AddIndex(
            model_name='solarcomponent',
            index=models.Index(fields=['wattage'], name='solar_confi_wattage_ade925_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configurationitem',
            unique_together={('configuration', 'component')},
        ),
        migrations.AlterUniqueTogether(
            name='packagecomponent',
            unique_together={('package', 'component')},
        ),
    ]
