# Generated by Django 5.0.14 on 2026-03-16 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solarcomponent',
            name='shop_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='Visible in the shop frontend'),
        ),
        migrations.AddField(
            model_name='solarcomponent',
            name='xlsx_row_key',
            field=models.CharField(blank=True, db_index=True, help_text='Key for XLSX seeding', max_length=200),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='distance_km',
            field=models.DecimalField(decimal_places=1, default=10, max_digits=8),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='inverter_kva',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Inverter kVA rating', max_digits=6),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='panel_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='phase',
            field=models.CharField(choices=[('1P', 'Single Phase'), ('3P', 'Three Phase')], default='1P', max_length=5),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='sundries_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='variant_name',
            field=models.CharField(blank=True, help_text='e.g. "V1.0", "V2.1", "Performance"', max_length=100),
        ),
        migrations.CreateModel(
            name='PackageFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kva_rating', models.DecimalField(decimal_places=1, help_text='kVA rating (e.g. 3.0, 5.0, 8.0)', max_digits=6)),
                ('family_code', models.CharField(help_text='e.g. "3kva", "5kva", "8kva"', max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('suitable_for', models.JSONField(blank=True, default=list, help_text='e.g. ["residential", "small_business"]')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Package Families',
                'ordering': ['sort_order', 'kva_rating'],
            },
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='solar_config.packagefamily'),
        ),
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('lighting', 'Lighting'), ('kitchen', 'Kitchen'), ('entertainment', 'Entertainment'), ('cooling', 'Cooling & Heating'), ('laundry', 'Laundry & Cleaning'), ('water', 'Water & Pumps'), ('office', 'Office & Computing'), ('security', 'Security'), ('outdoor', 'Outdoor & Garden'), ('other', 'Other')], db_index=True, max_length=20)),
                ('icon_name', models.CharField(blank=True, help_text='Phosphor icon name for frontend', max_length=50)),
                ('typical_wattage', models.PositiveIntegerField(default=0, help_text='Typical wattage draw')),
                ('power_points', models.DecimalField(decimal_places=2, default=0, help_text='PP score', max_digits=5)),
                ('energy_points', models.DecimalField(decimal_places=2, default=0, help_text='EP score', max_digits=5)),
                ('concurrency_factor', models.DecimalField(decimal_places=2, default=1, help_text='Concurrency factor (0-1)', max_digits=3)),
                ('night_use_factor', models.DecimalField(decimal_places=2, default=0, help_text='Night use factor (0-1)', max_digits=3)),
                ('smart_load_eligible', models.BooleanField(default=False, help_text='Can be deferred/scheduled')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='solar_confi_categor_20ef5c_idx')],
            },
        ),
    ]
