# Generated by Django 5.1.15 on 2026-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0003_appliance_room_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.CharField(choices=[('lounge', 'Lounge'), ('kitchen', 'Kitchen'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('laundry', 'Laundry'), ('office', 'Office'), ('garage', 'Garage & Workshop'), ('outdoor', 'Outdoor'), ('security', 'Security'), ('other', 'Other')], db_index=True, max_length=20),
        ),
    ]
