# Generated by Django 5.1.15 on 2026-04-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0004_change_appliance_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='comfort_class',
            field=models.CharField(choices=[('budget', 'Budget'), ('balanced', 'Balanced'), ('premium', 'Premium')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='ep_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum EP this package serves', max_digits=5),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='ep_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum EP this package serves', max_digits=5),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='inverter_brand',
            field=models.CharField(blank=True, help_text='must, growatt, sunsynk', max_length=50),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='management_tolerance',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='pp_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum PP this package serves', max_digits=5),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='pp_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum PP this package serves', max_digits=5),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='recharge_class',
            field=models.CharField(choices=[('basic', 'Basic'), ('moderate', 'Moderate'), ('balanced', 'Balanced'), ('strong', 'Strong'), ('premium', 'Premium')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='smart_load_supported',
            field=models.BooleanField(default=False, help_text='Inverter supports smart load scheduling'),
        ),
        migrations.AddField(
            model_name='solarpackagetemplate',
            name='variant_code',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. HE-1, HL-1', max_length=10),
        ),
    ]
