# Generated by Django 5.0.14 on 2026-04-13 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0005_add_capability_bands'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_pp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_ep', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('distance_km', models.DecimalField(decimal_places=1, default=10, max_digits=8)),
                ('appliance_count', models.PositiveIntegerField(default=0)),
                ('budget_package', models.CharField(blank=True, max_length=200)),
                ('good_fit_package', models.CharField(blank=True, max_length=200)),
                ('excellent_package', models.CharField(blank=True, max_length=200)),
                ('priority', models.CharField(blank=True, max_length=30)),
                ('use_style', models.CharField(blank=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstantQuoteDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=200)),
                ('tier_label', models.CharField(blank=True, max_length=50)),
                ('distance_km', models.DecimalField(decimal_places=1, default=10, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=30)),
                ('customer_address', models.CharField(blank=True, max_length=300)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_downloads', to='solar_config.solarpackagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
