# Generated by Django 5.0.14 on 2026-04-14 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0006_add_quote_tracking_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantquotedownload',
            name='appliances',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instantquotedownload',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_downloads', to='solar_config.recommendationsession'),
        ),
        migrations.AddField(
            model_name='recommendationsession',
            name='appliances',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
