# Generated by Django 5.0.14 on 2026-06-10 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0007_quote_session_linkage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('added', 'Added'), ('swapped', 'Swapped'), ('quantity', 'Quantity changed'), ('removed', 'Removed')], max_length=20)),
                ('from_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('to_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('reverted', models.BooleanField(default=False)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_changes', to=settings.AUTH_USER_MODEL)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='solar_config.solarcomponent')),
                ('from_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='solar_config.solarcomponent')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_log', to='solar_config.solarpackagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package', '-created_at'], name='solar_confi_package_5a8061_idx')],
            },
        ),
    ]
