# Generated by Django 5.0.14 on 2026-06-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_material_markup_pct'),
        ('solar_config', '0008_packagechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarcomponent',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solar_components', to='inventory.material'),
        ),
    ]
