# Generated by Django 5.0.14 on 2026-08-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0009_solarcomponent_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGuideSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_youtube_url', models.CharField(blank=True, max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Package guide setting',
                'verbose_name_plural': 'Package guide setting',
            },
        ),
        migrations.AddField(
            model_name='packagefamily',
            name='guide_youtube_url',
            field=models.CharField(blank=True, help_text='YouTube link for this family’s video selection guide. Blank shows a "Video coming soon" state on the site.', max_length=500),
        ),
    ]
