# Generated by Django 5.0.14 on 2026-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_config', '0010_packageguidesetting_packagefamily_guide_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageguidesetting',
            name='solar_advisor_youtube_url',
            field=models.CharField(blank=True, help_text='“How to use the Solar Advisor” guide shown on the advisor page.', max_length=500),
        ),
    ]
