# Generated by Django 5.1.15 on 2026-03-02 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway', models.CharField(choices=[('paynow', 'Paynow'), ('stripe', 'Stripe')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payment_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gateway', models.CharField(choices=[('paynow', 'Paynow'), ('stripe', 'Stripe'), ('cash', 'Cash')], max_length=20)),
                ('method', models.CharField(choices=[('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card'), ('cash', 'Cash')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_redirect', 'Awaiting Redirect'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('ZWG', 'Zimbabwe Gold')], default='USD', max_length=3)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=255)),
                ('gateway_poll_url', models.URLField(blank=True)),
                ('gateway_redirect_url', models.URLField(blank=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('stripe_client_secret', models.CharField(blank=True, max_length=255)),
                ('paynow_poll_url', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='payments_pa_content_23405f_idx'), models.Index(fields=['user', 'status'], name='payments_pa_user_id_01767a_idx'), models.Index(fields=['gateway', 'status'], name='payments_pa_gateway_fb31b8_idx')],
            },
        ),
    ]
