# Generated by Django 5.1.15 on 2026-04-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks'), ('bank_transfer', 'Bank Transfer'), ('zimswitch', 'ZimSwitch'), ('card', 'Card'), ('cash', 'Cash')], max_length=30),
        ),
    ]
