# Generated by Django 5.1.15 on 2026-04-14 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
        ('solar_config', '0007_quote_session_linkage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=255)),
                ('package_slug', models.CharField(blank=True, max_length=255)),
                ('tier_label', models.CharField(blank=True, max_length=50)),
                ('inverter_kva', models.CharField(blank=True, max_length=20)),
                ('battery_kwh', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=1, default=10, max_digits=8)),
                ('package_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('customer_address', models.CharField(blank=True, max_length=255)),
                ('terms_version', models.CharField(default='v2', max_length=20)),
                ('terms_accepted_at', models.DateTimeField()),
                ('terms_accepted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('converted', 'Converted to Invoice')], db_index=True, default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='solar_config.solarpackagetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Package Deposit',
                'verbose_name_plural': 'Package Deposits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_pa_user_id_719793_idx'), models.Index(fields=['status', '-created_at'], name='payments_pa_status_85c4ed_idx')],
            },
        ),
    ]
