# Generated by Django 5.1.15 on 2026-04-14 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_packagedeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedeposit',
            name='deposit_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
