# Generated by Django 5.1.15 on 2026-04-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_packagedeposit_deposit_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
